export const salons = [
  {
    id: "10",
    name: "Huvudstaden",
    slug: "huvudstaden",
    cutting_price: 390,
    cutting_time: "35",
    street: "Hjälmarvägen 89",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "20:00",
    },
    phone: "08–522 389 20",
    website: "www.huvudstaden.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 5,
    reviews_count: 50,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "1",
    name: "Sax & Fön",
    slug: "sax-fon",
    cutting_price: "300",
    cutting_time: "30",
    street: "Rådmansgatan 46",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "19:00",
    },
    phone: "08–522 389 20",
    website: "www.salongweb.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 3,
    reviews_count: 32,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "2",
    name: "Hårizont",
    slug: "harizont",
    cutting_price: "320",
    cutting_time: "30",
    street: "Hötorget 4",
    postal_address: "113 57 Stockholm",
    schedule: "12:30",
    opening_hours: {
      start: "10:00",
      end: "18:00",
    },
    phone: "08–522 389 20",
    website: "www.harizont.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 2,
    reviews_count: 3,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "3",
    name: "Hårhuset",
    slug: "harhuset",
    cutting_price: "300",
    cutting_time: "30",
    street: "Sveavägen 56",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "19:30",
    },
    phone: "08–522 389 20",
    website: "www.harhuset.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 4,
    reviews_count: 32,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "4",
    name: "Hair & Nu",
    slug: "hair-nu",
    cutting_price: "350",
    cutting_time: "30",
    street: "Hornsgatan 2",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "20:00",
    },
    phone: "08–522 389 20",
    website: "www.hairochnu.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 3,
    reviews_count: 32,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "5",
    name: "Hårley Davidson",
    slug: "harley-davidson",
    cutting_price: "360",
    cutting_time: "40",
    street: "Götgatan 46",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "18:30",
    },
    phone: "08–522 389 20",
    website: "www.harleydavidson.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 3,
    reviews_count: 55,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "6",
    name: "Frisörerna",
    slug: "frisorerna",
    cutting_price: "300",
    cutting_time: "30",
    street: "Skånegatan 46",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "19:00",
    },
    phone: "08–522 389 20",
    website: "www.frisorerna.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 4,
    reviews_count: 2,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "7",
    name: "Hår mår du",
    slug: "har-mar-du",
    cutting_price: "290",
    cutting_time: "20",
    street: "Östersjövägen 46",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "19:30",
    },
    phone: "08–522 389 20",
    website: "www.hur-mar-du-salong.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 5,
    reviews_count: 14,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "8",
    name: "Klippet",
    slug: "klippet",
    cutting_price: "340",
    cutting_time: "35",
    street: "Klippvägen 46",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "18:00",
    },
    phone: "08–522 389 20",
    website: "www.klippet.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 3,
    reviews_count: 13,
    img_url: "/images/image@3x.jpg",
  },
  {
    id: "9",
    name: "Frisyrfrisörerna",
    slug: "frisyrfrisorerna",
    cutting_price: "340",
    cutting_time: "35",
    street: "Friskisvägen 3",
    postal_address: "113 57 Stockholm",
    schedule: "12:00",
    opening_hours: {
      start: "10:00",
      end: "20:00",
    },
    phone: "08–522 389 20",
    website: "www.frisyrfrisorerna.se",
    description:
      "Lorem ipsum dolor sit amet, vulputate nunc. Auctor viverra. Ridiculus feugiat nunc porttitor volut pat, acu quis torquent iaculis ultricies massa, duis nun quis que amet.",
    rating: 3,
    reviews_count: 13,
    img_url: "/images/image@3x.jpg",
  },
];
